version: "3.8"

services:
  database:
    hostname: database
    build:
      context: ./provision/docker/database
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m
      timeout: 10s
      retries: 3

  backend:
    hostname: backend
    init: true
    build:
      context: ./provision/docker/backend
      target: develop
    depends_on:
      - database
    volumes:
      - ".:/app"
      - "home:/home/app"
      - "pyenv:/python"
    ports:
      - "8000:8000"

volumes:
  pgdata:
  home:
  pyenv:
