[tool.black]
line-length = 100
target-version = ['py39']
exclude = '''
/(
    \.git
  | venv
  | node_modules
  | migrations
  | templates
  } static
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
combine_as_imports = true
include_trailing_comma = true
line_length = 100
default_section = "THIRDPARTY"
known_first_party = "aseb"
src_paths = ["src/aseb", "test"]
skip = ["migrations", "node_modules", "templates", "venv"]
