# Generated by Django 3.2.6 on 2021-08-22 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Required. 50 characters or fewer. Letters, digits and -/_ only.', max_length=50, validators=[django.core.validators.RegexValidator('^[\\w_\\-.]+\\Z')], verbose_name='username'),
        ),
    ]
