# Generated by Django 3.2.6 on 2021-08-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="jwt_jti",
            field=models.CharField(blank=True, editable=False, max_length=256),
        ),
    ]
