# Generated by Django 3.2.6 on 2021-08-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_accesstoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstoken",
            name="expires",
            field=models.DateTimeField(null=True),
        ),
    ]
