# Generated by Django 3.2.6 on 2021-08-19 05:29

from django.db import migrations, models
import django.db.models.functions.datetime
import django_editorjs_fields.fields
import django_ltree.fields
import aseb.core.db.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_ltree", "__latest__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", django_ltree.fields.PathField(unique=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now, editable=False
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("removed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=100)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=300)),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=aseb.core.db.utils.UploadToFunction(
                            "{model_name}/{obj.pk}/{filename}.{ext}"
                        ),
                    ),
                ),
                ("content", django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True)),
                ("redirect_to", models.URLField(blank=True)),
            ],
            options={
                "ordering": ("path",),
            },
        ),
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now, editable=False
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("removed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("hostname", models.CharField(max_length=40, unique=True)),
                ("aliases", models.CharField(blank=True, max_length=140)),
                ("name", models.CharField(max_length=140)),
                ("tagline", models.CharField(blank=True, max_length=140)),
                ("description", models.CharField(blank=True, max_length=280)),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        upload_to=aseb.core.db.utils.UploadToFunction(
                            "websites/{obj.pk}/{filename}.{ext}"
                        ),
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("publish", "Published"), ("publishing", "Publishing")],
                        default="publish",
                        max_length=10,
                    ),
                ),
                ("search_description", models.CharField(blank=True, max_length=140)),
                (
                    "allow_searchengine",
                    models.BooleanField(verbose_name="Visible to search engines"),
                ),
                (
                    "reader_access",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private, require authentication"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("custom_robots_txt", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
                "default_permissions": ("view", "add", "change", "delete", "remove"),
            },
        ),
    ]
