# Generated by Django 3.2.6 on 2021-08-19 05:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime
import django_editorjs_fields.fields
import aseb.core.db.fields
import aseb.core.db.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now, editable=False
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("removed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("contact_phone", models.CharField(blank=True, max_length=40)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("location_city", models.CharField(blank=True, max_length=100)),
                ("location_country", models.CharField(blank=True, max_length=100)),
                ("link_facebook", models.CharField(blank=True, max_length=200)),
                ("link_instagram", models.CharField(blank=True, max_length=200)),
                ("link_linkedIn", models.CharField(blank=True, max_length=200)),
                ("link_website", models.CharField(blank=True, max_length=200)),
                ("link_twitter", models.CharField(blank=True, max_length=200)),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=300)),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=aseb.core.db.utils.UploadToFunction(
                            "{model_name}/{obj.pk}/{filename}.{ext}"
                        ),
                    ),
                ),
                ("content", django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ("headline", models.CharField(blank=True, max_length=140)),
                ("presentation", models.TextField(blank=True)),
                (
                    "size",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - 4 employees"),
                            (2, "5 - 9 employees"),
                            (3, "10 - 19 employees"),
                            (4, "20 - 49 employees"),
                            (5, "50 - 99 employees"),
                            (6, "100 - 249 employees"),
                            (7, "250 - 499 employees"),
                            (8, "500 - 999 employees"),
                            (9, "1,000+ employees"),
                        ],
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
            },
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "emoji",
                    models.CharField(
                        max_length=1,
                        validators=[
                            django.core.validators.RegexValidator(
                                "(\\u00a9|\\u00ae|[\\u2000-\\u3300]|\\ud83c[\\ud000-\\udfff]|\\ud83d[\\ud000-\\udfff]|\\ud83e[\\ud000-\\udfff])"
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now, editable=False
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("removed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("contact_phone", models.CharField(blank=True, max_length=40)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("location_city", models.CharField(blank=True, max_length=100)),
                ("location_country", models.CharField(blank=True, max_length=100)),
                ("link_facebook", models.CharField(blank=True, max_length=200)),
                ("link_instagram", models.CharField(blank=True, max_length=200)),
                ("link_linkedIn", models.CharField(blank=True, max_length=200)),
                ("link_website", models.CharField(blank=True, max_length=200)),
                ("link_twitter", models.CharField(blank=True, max_length=200)),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=300)),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=aseb.core.db.utils.UploadToFunction(
                            "{model_name}/{obj.pk}/{filename}.{ext}"
                        ),
                    ),
                ),
                ("content", django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                (
                    "id",
                    aseb.core.db.fields.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=140)),
                ("last_name", models.CharField(blank=True, max_length=140)),
                ("display_name", models.CharField(blank=True, max_length=140)),
                ("headline", models.CharField(blank=True, max_length=140)),
                ("presentation", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("partnerIndividual", "Individual Partner"),
                            ("partnerCorporate", "Corporate Partner"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("president", "President"),
                            ("advisor", "Advisor"),
                            ("boardMember", "Board Member"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("activated_at", models.DateField(blank=True, null=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="organization.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": ("view", "add", "change", "delete", "remove"),
            },
        ),
    ]
