# Generated by Django 3.2.6 on 2021-08-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="company",
            name="markets",
        ),
        migrations.RemoveField(
            model_name="member",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="member",
            name="markets",
        ),
        migrations.RemoveField(
            model_name="member",
            name="mentor_interests",
        ),
        migrations.RemoveField(
            model_name="member",
            name="mentor_markets",
        ),
        migrations.AddField(
            model_name="company",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="_organization_company_topics_+", to="organization.Topic"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="mentor_topics",
            field=models.ManyToManyField(
                blank=True,
                related_name="_organization_member_mentor_topics_+",
                to="organization.Topic",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="_organization_member_topics_+", to="organization.Topic"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
    ]
