# Generated by Django 3.2.6 on 2021-08-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_auto_20210827_1900"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="event",
            name="markets",
        ),
        migrations.RemoveField(
            model_name="serie",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="serie",
            name="markets",
        ),
        migrations.AddField(
            model_name="event",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="_events_event_topics_+", to="organization.Topic"
            ),
        ),
        migrations.AddField(
            model_name="serie",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="_events_serie_topics_+", to="organization.Topic"
            ),
        ),
    ]
