# Generated by Django 3.2.6 on 2021-08-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="topic",
        ),
        migrations.AddField(
            model_name="post",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="_posts_post_topics_+", to="organization.Topic"
            ),
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
