name: Build docker image

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v2
        with:
          push: true
          context: provision/docker/backend
          tags: ghcr.io/somosaseb/somosaseb-api/base:latest
          cache-from: type=registry,ref=ghcr.io/somosaseb/somosaseb-api/base:latest
          cache-to: type=inline

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/somosaseb/somosaseb-api:latest
          cache-from: type=registry,ref=ghcr.io/somosaseb/somosaseb-api:latest
          cache-to: type=inline
